version: "4"
dependencies:
  - mlflow>=3.7

  # TRL and dependencies
  - trl>=0.12.0
  - peft>=0.13.0
  - transformers>=4.46.0

  # Fix HuggingFace Hub / fsspec compatibility issue
  - huggingface_hub>=0.25.0
  - datasets>=3.0.0
  - fsspec>=2024.6.0